name: Test
on:
  pull_request:
    paths: ['src/main/kotlin/**/*.kt']
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
#      - uses: fwilhe2/setup-kotlin@main
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Grant gradle permission
        run: chmod +x ./gradlew

      - name: Run test
        run: ./gradlew test